openapi: 3.0.0
info:
  title: API For Places
  version: 1.0.0
paths:
  /places:
    post:
      summary: Create a new place
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                location:
                  type: string
                openHours:
                  type: string
                images:
                  type: array
                  items:
                    type: string
                    format: binary
    get:
      summary: Get all places
  /places/{id}:
    get:
      summary: Get a place by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
    UPDATE PLACE:
      summary: Update a place by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                location:
                  type: string
                openHours:
                  type: string
                images:
                  type: array
                  items:
                    type: string
                    format: binary
    delete:
      summary: Delete a place by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
